### PR TITLE
Styled components for css-in-js and removed Font-awsome for react-icons

### PR DESCRIPTION
**Pull request by revengemiroz**
Things done
1. Removed Font awsome cause its huge library for only 2 icons used and opted to React-icons.
2. Stylling was done in the index.css now it uses styled components
3. Better folder structure for components

### CODE REVIEW

**Review by nomanoff — APPROVED** [review]
Good job

**Comment by revengemiroz** [comment]
will this be merged into master ?

**Comment by nomanoff** [comment]
I merged it and then there was a merge conflict. Then I had to reverse back. I think there was a conflict because just before you somebody's pull request was merged and then when I merged yours there was a conflict. That's why your changes aren't showing

**Comment by nomanoff** [comment]
I tried to fix the conflict but it was too complicated for me to solve. I am also new to this react. I am so sorry for that

**Pull request merged**
